import { Platform } from 'react-native';

export const Icons = {
  icon_language_select: require('../../assets/icons/language_icon.png'),
  icon_back: require('../../assets/icons/back_icon.png'),
  icon_arrow_right: require('../../assets/icons/arrow_right.png'),
  icon_arrow_up: require('../../assets/icons/arrow_up.png'),
  icon_arrow_down: require('../../assets/icons/arrow_down.png'),
  icon_tick: require('../../assets/icons/tick.png'),
  icon_tick_circle: require('../../assets/icons/tick_circle.png'),
  icon_close: require('../../assets/icons/close.png'),
  icon_triangle_down: require('../../assets/icons/triangle_down.png'),
  icon_triangle_up: require('../../assets/icons/triangle_up.png'),
  icon_facebook: require('../../assets/icons/facebook.png'),
  icon_line: require('../../assets/icons/line.png'),
  icon_google: require('../../assets/icons/googleplus.png'),
  icon_twitter: require('../../assets/icons/twitter.png'),
  icon_flag_america: require('../../assets/icons/flag_america.png'),
  icon_flag_china: require('../../assets/icons/flag_china.png'),
  icon_flag_korea: require('../../assets/icons/flag_korea.png'),
  icon_flag_japan: require('../../assets/icons/flag_japan.png'),
  icon_flag_taiwan: require('../../assets/icons/flag_taiwan.png'),
  icon_menu: require('../../assets/icons/menu.png'),
  icon_home: require('../../assets/icons/home.png'),
  icon_home_active: require('../../assets/icons/home_color.png'),
  icon_home_select: require('../../assets/icons/home_select.png'),
  icon_chat: require('../../assets/icons/chat.png'),
  icon_chat_select: require('../../assets/icons/chat_select.png'),
  icon_more: require('../../assets/icons/more.png'),
  icon_more_select: require('../../assets/icons/more_select.png'),
  icon_timeline: require('../../assets/icons/timeline.png'),
  icon_timeline_select: require('../../assets/icons/timeline_select.png'),
  icon_channel: require('../../assets/icons/channel.png'),
  icon_channel_select: require('../../assets/icons/channel_select.png'),
  icon_message: require('../../assets/icons/message.png'),
  icon_scenario: require('../../assets/icons/scenario.png'),
  icon_camera: require('../../assets/icons/camera.png'),
  icon_pencil: require('../../assets/icons/pencil.png'),
  icon_alert: require('../../assets/icons/alert.png'),
  icon_edit_pen: require('../../assets/icons/edit_icon.png'),
  icon_search: require('../../assets/icons/search.png'),
  icon_dots: require('../../assets/icons/dots.png'),
  icon_create_group_chat: require('../../assets/icons/CreateGroupChat.png'),
  icon_create_new_channel: require('../../assets/icons/CreateNewChannel.png'),
  icon_upload: require('../../assets/icons/upload.png'),
  icon_send_button: require('../../assets/icons/send_button.png'),
  icon_camera_grad: require('../../assets/icons/camera_grad.png'),
};

export const Images = {
  image_touku_bg: require('../../assets/images/touku_bg_new.png'),
  image_default_profile: require('../../assets/images/default_profile.png'),
  image_home_bg: require('../../assets/images/touku_home_bg.png'),
  image_loading: require('../../assets/images/loading.gif'),
  image_gallery: require('../../assets/images/gallery.png'),
};

export const Colors = {
  primary: '#ef4f8f',
  white: '#ffffff',
  black: '#000000',
  gradient_1: '#ef4f8f',
  gradient_2: '#f27478',
  gradient_3: '#f68b6b',
  orange: '#fd7e14',
  gray: '#dcdcdc',
  gray_dark: '#6c757d',
  danger: '#DC3545',
  home_header: '#fb9a7a',
  indigo: '#6610f2',
  purple: '#6f42c1',
  green: '#1bd078',
};

export const Fonts = {
  regular: 'Poppins-Regular',
  medium: 'Poppins-Medium',
  thin: 'Poppins-Thin',
  light: 'Poppins-Light',
  semibold: 'Poppins-SemiBold',
  bold: 'Poppins-Bold',
  black: 'Poppins-Black',
  extralight: 'Poppins-ExtraLight',
  extrabold: 'Poppins-ExtraBold',
  absolute: Platform.OS === 'ios' ? 'The Absolute' : 'The-Absolute',
};
